CLASS /eacm/bp_i_rpdettmde DEFINITION
  PUBLIC
  ABSTRACT
  FINAL FOR BEHAVIOR OF /eacm/i_rpdettmde.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS /eacm/bp_i_rpdettmde IMPLEMENTATION.
ENDCLASS.
